### ISSUE TITLE
Documentation: Document Selenium usage

### ISSUE THREAD

**Issue by IngwiePhoenix** [anime-dl/anime-downloader#478]
I noticed that aside from cfscrape, Selenium was added to deal with CloudFlare - but the documentation ( https://anime-downlader.readthedocs.io/en/latest/index.html ) hasn't been updated, unfortunately.

Hence, I'd like to request an update for the `selescrape_*` config values.

**Comment by nate-moo** [comment]
@ArjixGamer

**Comment by ArjixGamer** [comment]
ok, will do, either today or tomo

**Comment by ArjixGamer** [comment]
wait, selenium is used as a replacement for cfscrape, you can just normally replace the cf=True with sel=True, i dont think we have working post requests, ask @Blatzar . But its pretty much the same
```python
from anime_downloader.sites import helpers
url = "https://example.com"
r = helpers.get(url, sel=True)
soup = helpers.soupify(r)
```

**Comment by ArjixGamer** [comment]
oh, you want the config values, sorry my bad

**Comment by ArjixGamer** [comment]
ill add it to the docs too but here you go:
```python
Selescrape options: {
"selescrape_driver_binary_path" : None,
"selescrape_browser_executable_path": None,
"selescrape_browser": None
}
```
**selescrape_driver_binary_path**: is for the user to specify the WebDriver binary path (eg geckodriver/chromedriver.exe) in case the WebDriver is not in PATH or there are more than 1 installation of that WebDriver

**selescrape_browser_executable_path**: as the name suggests it is the browsers main executable filepath, incase the browser is not in PATH or there are more than 1 installations of that browser

**selescrape_browser**: here you specify the browser you want to use, possible values ["chrome", "firefox"]

Unless you ever have problems with SeleScrape then you dont need to change any of the above config, because all of those settings are decided with code logic during runtime if the value they have is None/null.
