### ISSUE TITLE
Implementing MAL API instead of watch list implementation

### ISSUE THREAD

**Issue by Skaytacium** [anime-dl/anime-downloader#575]
### What it is

Implementing the MAL API instead of making users have to export their MAL list and import it all of the time.

### Why?

Lots of benefits:
- Updating user anime list and importing every time anime watch is used, so any changes are synchronized
- No need for XML parser in import, instead a new script could handle API (slightly counterintuitive but shouldn't matter as its one time)
- Updating doesn't have to be real-time, could be done every time user asks or `anime watch` is used
- Being able to recommend anime based on the watch history
- Scalable

There are some downsides, like:
- Need for another script
- ~~Authentication~~ This is managed by the API by using user authentication  and OAuth2
- ~~Security (as its open-source)~~ This is also managed by the API as it has options for these kinds of situations

### Pull request?

I could personally work on it in a separate branch, but as python isn't my main language (its javascript/typescript) I might need some help, and then issue a pull request which could be merged into the master branch

### Conclusion

It should be a great feature which will make anime-downloader a more powerful application and help out lots of people

### Edits

1. Adding a pull request as I already created an application for the MAL API
2. I realized there are many fields that cannot be filled by me, therefore I am deleting my app. Also changed downsides (sorry for the extra text)

**Comment by IguanasInPyjamas** [comment]
I feel like this needs to be an addition, not a change.

For example, I exported from MAL and now keep a local updated offline store which with another script gives me a human readable de-centralised anime list - instead of relying on MAL. For me, keeping the MAL import makes sense.

Now, the real benefit of your approach in my opinion is syncing to mal with;
1 - The watch list 
2 - Anytime a user uses --play with `anime dl`
3 - an option to sync to mal with `anime gui` 

MAL implementation is highly saught after in this project to be honest, and it would be great if a PR could be made to tackle this.

**Comment by Skaytacium** [comment]
I would not mind at all, but I would need some support from the dev team in terms of creating the API. I can handle the coding part, I just need some information about the app which I cannot obtain.

What I need is given in the following image:

![image](https://user-images.githubusercontent.com/58383260/99927469-828d9700-2d6b-11eb-9805-f03675e25911.png)

For any further contact, my discord is Skayatcium#9690

**Comment by IguanasInPyjamas** [comment]
Join the anime-dl discord and I'll hook you up with that information asap.
