### ISSUE TITLE
Download Manager

### ISSUE THREAD

**Issue by Vedabahu** [anime-dl/anime-downloader#668]
How can I use IDM as external download manager for downloading anime. Or is there any option to change split size and max number of connections to server in aria2 while downloading? Or can you add an option to create a txt file to paste all links of episodes in different lines so then we can download manually.

**Comment by ArjixGamer** [comment]
> How can I use IDM as external download manager for downloading anime. 

Now listen closely because I won't say it again,
Change the external downloader to ``{idm}``  *how to do that you ask? simple, edit the config*
And make sure the IDMan executable is on path.

Google search how to add this folder to ur PATH variable
``C:\Program Files (x86)\Internet Download Manager``
At least thats the folder where IDM is installed for me.

> Or can you add an option to create a txt file to paste all links of episodes in different lines so then we can download manually.

Have you ever heard of piping output to a file?
It's really simple, just run an anime dl command that prints the links and pipe the output to a file
For example:
```cmd
anime dl "overlord" -u > episodes.txt
```

It will create a file with an episode link per line.


> Or is there any option to change split size and max number of connections to server in aria2 while downloading?

This is not a configurable setting, it is hard coded in anime dl.
